"""
WAF Detector - Fingerprint Web Application Firewalls from HTTP responses.

Usage:
    python utils/waf_detector.py --target "http://target.com/page.php?id=1"
    python utils/waf_detector.py --target "http://target.com" --probe
"""

import argparse
import re
import sys

try:
    import requests
    requests.packages.urllib3.disable_warnings()
except ImportError:
    print("[!] Install requests: pip install requests")
    sys.exit(1)


WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": [
            ("server", "cloudflare"),
            ("cf-ray", None),
            ("cf-cache-status", None),
        ],
        "body": [
            r"cloudflare",
            r"Ray ID: [0-9a-f]{16}",
            r"Attention Required! \| Cloudflare",
        ],
        "status_codes": [403, 503],
    },
    "ModSecurity": {
        "headers": [
            ("server", "mod_security"),
        ],
        "body": [
            r"Mod_Security",
            r"NAXSI",
            r"ModSecurity",
            r"This error was generated by Mod_Security",
        ],
        "status_codes": [403, 406],
    },
    "Imperva (Incapsula)": {
        "headers": [
            ("x-cdn", "incapsula"),
            ("x-iinfo", None),
        ],
        "body": [
            r"Incapsula incident ID",
            r"incapsula",
            r"_Incapsula_Resource",
        ],
        "status_codes": [403],
    },
    "F5 BIG-IP ASM": {
        "headers": [
            ("x-wa-info", None),
        ],
        "body": [
            r"The requested URL was rejected",
            r"BIG-IP",
            r"F5 Networks",
        ],
        "status_codes": [403],
    },
    "Akamai": {
        "headers": [
            ("server", "akamaighost"),
            ("x-check-cacheable", None),
        ],
        "body": [
            r"Reference #[0-9a-f.]+",
            r"Akamai",
            r"access denied",
        ],
        "status_codes": [403],
    },
    "Sucuri": {
        "headers": [
            ("x-sucuri-id", None),
            ("x-sucuri-cache", None),
        ],
        "body": [
            r"Sucuri Website Firewall",
            r"Access Denied - Sucuri",
        ],
        "status_codes": [403],
    },
    "Barracuda": {
        "headers": [
            ("x-barracuda-appid", None),
        ],
        "body": [
            r"Barracuda",
            r"barra_counter_session",
        ],
        "cookies": ["barra_counter_session"],
        "status_codes": [400, 403],
    },
    "AWS WAF": {
        "headers": [
            ("x-amzn-requestid", None),
            ("x-amz-cf-id", None),
        ],
        "body": [
            r"AWS WAF",
            r"Request blocked",
        ],
        "status_codes": [403],
    },
    "Fortinet FortiWeb": {
        "headers": [],
        "body": [
            r"FortiWeb",
            r"Web Application Firewall - Fortinet",
            r"The web server is temporarily unable to service",
        ],
        "status_codes": [403],
    },
    "Citrix NetScaler": {
        "headers": [
            ("via", "NS-CACHE"),
            ("x-nsprotect", None),
        ],
        "body": [
            r"NetScaler",
            r"ns_af",
        ],
        "cookies": ["st8id", "ns_af"],
        "status_codes": [403],
    },
}

PROBE_PAYLOADS = [
    "' OR '1'='1",
    "1 UNION SELECT 1,2,3--",
    "1 AND 1=1",
    "'; DROP TABLE test--",
    "1; SELECT SLEEP(0)--",
]


class WAFDetector:
    def __init__(self, target_url, timeout=10, verify_ssl=False):
        self.target_url = target_url
        self.timeout = timeout
        self.verify_ssl = verify_ssl
        self.session = requests.Session()
        self.session.headers.update({
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        })

    def get_baseline(self):
        """Fetch baseline response (no injection)."""
        try:
            resp = self.session.get(
                self.target_url,
                timeout=self.timeout,
                verify=self.verify_ssl,
                allow_redirects=True
            )
            return resp
        except requests.RequestException as e:
            print(f"[!] Baseline request failed: {e}")
            return None

    def probe_waf(self):
        """Send malicious payload to trigger WAF."""
        results = []
        for payload in PROBE_PAYLOADS:
            url = self.target_url
            if "?" in url:
                url = url + payload
            else:
                url = url + "?id=" + payload

            try:
                resp = self.session.get(
                    url,
                    timeout=self.timeout,
                    verify=self.verify_ssl,
                    allow_redirects=True
                )
                results.append(resp)
            except requests.RequestException:
                pass

        return results

    def fingerprint(self, response):
        """Identify WAF from a response."""
        if response is None:
            return []

        detected = []
        headers = {k.lower(): v.lower() for k, v in response.headers.items()}
        body = response.text.lower()
        cookies = [c.lower() for c in response.cookies.keys()]

        for waf_name, sigs in WAF_SIGNATURES.items():
            score = 0

            # Check headers
            for header_name, header_value in sigs.get("headers", []):
                if header_name in headers:
                    if header_value is None or header_value in headers[header_name]:
                        score += 3

            # Check body patterns
            for pattern in sigs.get("body", []):
                if re.search(pattern.lower(), body):
                    score += 2

            # Check cookies
            for cookie_name in sigs.get("cookies", []):
                if cookie_name.lower() in cookies:
                    score += 2

            # Check status code
            if response.status_code in sigs.get("status_codes", []):
                score += 1

            if score >= 3:
                detected.append((waf_name, score))

        return sorted(detected, key=lambda x: x[1], reverse=True)

    def detect(self, probe=False):
        """Main detection flow."""
        print(f"[*] Target: {self.target_url}")

        baseline = self.get_baseline()
        if baseline:
            print(f"[*] Baseline: HTTP {baseline.status_code}")

        if probe:
            print("[*] Probing with SQL injection payloads...")
            probe_responses = self.probe_waf()
        else:
            probe_responses = [baseline] if baseline else []

        all_detected = {}
        for resp in probe_responses:
            for waf_name, score in self.fingerprint(resp):
                if waf_name not in all_detected or score > all_detected[waf_name]:
                    all_detected[waf_name] = score

        if all_detected:
            print("\n[+] WAF DETECTED:")
            for waf, score in sorted(all_detected.items(), key=lambda x: x[1], reverse=True):
                print(f"    {waf} (confidence: {score})")
            return list(all_detected.keys())
        else:
            print("\n[-] No WAF detected (or unrecognized WAF)")
            return []

    def get_tamper_recommendation(self, waf_names):
        """Return tamper script recommendations for detected WAFs."""
        recommendations = {
            "Cloudflare": "space2comment,randomcase,charencode",
            "ModSecurity": "modsecurityzeroversioned,space2comment,randomcase",
            "Imperva (Incapsula)": "space2comment,randomcase,between,greatest,charencode",
            "F5 BIG-IP ASM": "randomcase,charencode,space2randomblank",
            "Akamai": "between,chardoubleencode,randomcase,space2comment",
            "Sucuri": "space2comment,randomcase",
            "Barracuda": "percentage,randomcase,space2comment",
            "AWS WAF": "charencode,randomcase,between,space2comment",
            "Fortinet FortiWeb": "space2comment,randomcase,charencode",
            "Citrix NetScaler": "space2comment,between,randomcase",
        }

        result = []
        for waf in waf_names:
            if waf in recommendations:
                result.append(recommendations[waf])

        if result:
            return result[0]  # Return first match
        return "space2comment,randomcase"  # Generic fallback


def main():
    parser = argparse.ArgumentParser(description="WAF Detection Tool for SQLMap")
    parser.add_argument("--target", required=True, help="Target URL")
    parser.add_argument("--probe", action="store_true", help="Probe with SQL payloads")
    parser.add_argument("--recommend", action="store_true", help="Show tamper recommendations")
    args = parser.parse_args()

    detector = WAFDetector(args.target)
    detected_wafs = detector.detect(probe=args.probe)

    if args.recommend and detected_wafs:
        tampers = detector.get_tamper_recommendation(detected_wafs)
        print(f"\n[*] Recommended tamper chain:")
        print(f"    --tamper={tampers}")
        print(f"\n[*] Full SQLMap command:")
        print(f"    sqlmap -u \"{args.target}\" --tamper={tampers} --random-agent --delay=2 --batch")


if __name__ == "__main__":
    main()
